name: Seguridad_20220592
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^6.0.0
  dotted_border: ^2.1.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/yosoy.jpg
